#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/20-php-fpm ]; then
sleep 1

	### Start php-fpm
	mkdir -p /www/logs/php-fpm
	chown -R nginx /www/logs/php-fpm
	mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/20-php-fpm
    
fi

echo ''
echo '** Starting php-fpm..'
exec s6-setuidgid nginx php-fpm7 -F;
